Cypress.Commands.add('registerNewUser', (email, password) => {
    cy.get('#reg_email')
        .type(email)
    cy.get('#reg_password')
        .type(`${password}{enter}`)
})

Cypress.Commands.add('login', (email, password) => {
    cy.get('#username')
        .type(email)
    cy.get('#password')
        .type(`${password}{enter}`, { log: false })
});

Cypress.Commands.add('addProductToCart', (productName, size, color, quantity) => {
    cy.get('[class = "product-block grid"]')
        .contains(productName)
        .click()
    cy.get('.button-variable-item-' + size)
        .click()
    cy.get('.button-variable-item-' + color)
        .click()
    cy.get('.input-text')
        .clear()
        .type(quantity)
    cy.get('.single_add_to_cart_button')
        .click()
    cy.get('#primary-menu > .menu-item-629 > a')
        .click()
});

Cypress.Commands.add('checkoutFormFill', (name, lastName, country, address, city, state, zipCode, telephone) => {
    cy.get('#billing_first_name')
        .type(name)
    cy.get('#billing_last_name')
        .type(lastName)
    cy.get('#select2-billing_country-container')
        .click()
    cy.get('.select2-search__field')
        .type(`${country}{enter}`)
    cy.get('#billing_address_1')
        .type(address)
    cy.get('#billing_city')
        .type(city)
    cy.get('#select2-billing_state-container')
        .click()
        .type(`${state}{enter}`)
    cy.get('#billing_postcode')
        .type(zipCode)
    cy.get('#billing_phone')
        .type(telephone)
})